version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_BASE_URL=http://localhost:5999
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5999:5999"
    env_file: 
      - ./server/src/configs/.env  # Load .env file for MongoDB URI and other env variables
    depends_on:
      - mongodb  # Wait for MongoDB to be ready before starting the server

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"